# Configuración específica para desarrollo
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Scripts SQL iniciales - ORDEN IMPORTANTE: primero data.sql, luego data-security.sql
spring.sql.init.data-locations=classpath:data.sql,classpath:data-security.sql

# Logging detallado
logging.level.root=INFO
logging.level.com.meli.inventory_service=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
