# Configuración de SpringDoc/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true

# Configuración de Spring Security (solo para desarrollo)
spring:
  security:
    user:
      name: admin
      password: admin

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN
        orm:
          jdbc:
            bind: WARN
    # Opcional: nivel general de Hibernate
    # org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
