spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutos

logging:
  level:
    root: INFO
    com.meli: INFO
    org.hibernate: OFF
    org.hibernate.SQL: OFF
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.scheduling: WARN
    org.springframework.retry: DEBUG
