# Configuración específica para desarrollo
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.defer-datasource-initialization=true

# Scripts SQL iniciales - ORDEN IMPORTANTE: primero data.sql, luego data-security.sql
spring.sql.init.data-locations=classpath:data.sql,classpath:data-security.sql

# Logging - DESACTIVAR LOGS SQL PARA NO ENTORPECER LA LECTURA
logging.level.root=INFO
logging.level.com.meli.inventory_service=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.springframework.security=INFO
logging.level.org.springframework.scheduling=WARN

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
