spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: InventoryHikariPool
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutos
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false

logging:
  level:
    root: INFO
    com.meli: INFO
    org.hibernate: OFF
    org.hibernate.SQL: OFF
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.scheduling: WARN
    org.springframework.retry: WARN
    com.zaxxer.hikari: DEBUG
